alias planner="rtm planner today status:incomplete"
alias today="rtm ls list:Today"
alias todo="rtm ls list:Todo"
alias overdue="rtm ls duebefore:today status:incomplete"
alias inbox="rtm ls list:inbox"
