alias set_primary_display="xrandr --output DP-2 --primary"
alias wifi_off="nmcli nm wifi off"
alias wifi_on="nmcli nm wifi on"
alias vpn_off="nmcli c down id 'Biostat'"
alias vpn_on="nmcli c up id 'Biostat'"
