alias set_primary_display="xrandr --output DP-2 --primary"
alias wifi_off="nmcli nm wifi off"
alias wifi_on="nmcli nm wifi on"
alias vpn_off="nmcli c down id 'Biostat'"
alias vpn_on="nmcli c up id 'Biostat'"
alias win7="virt-viewer win7"
alias wireframe="env LIBOVERLAY_SCROLLBAR=0 UBUNTU_MENUPROXY=0 /opt/WireframeSketcher/WireframeSketcher"
